SELECT ?etfname (COUNT(?company) AS ?companyCount) (COUNT(?companyName) AS ?companyNameCount)
WHERE {
  ?etf a finance:ETF ;
       finance:hasName ?etfname ;
       finance:hasCompany ?company .
  ?company finance:hasName ?companyName .
}
GROUP BY ?etfname

