# get all persons and its name in a sparql query
# select count of persons that hasGender 'w' and 'm' and '' in a sparql query for me


SELECT ?gender (COUNT(?person) AS ?count)
WHERE {
  ?person a finance:Person .
  ?person finance:hasGender ?gender .
}
GROUP BY ?gender
